//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANTA_Punto_de_Venta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SANTAEntities : DbContext
    {
        public SANTAEntities()
            : base("name=SANTAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<descuento> descuentos { get; set; }
        public virtual DbSet<notas_credito> notas_credito { get; set; }
        public virtual DbSet<pagos_notas_credito> pagos_notas_credito { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<registro_notas_credito> registro_notas_credito { get; set; }
        public virtual DbSet<registro_ventas> registro_ventas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<venta_dia> venta_dia { get; set; }
    }
}
